"""on_production

Revision ID: 2815bcfd326f
Revises: ed145ac0fc3b
Create Date: 2022-01-08 22:49:39.389452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2815bcfd326f'
down_revision = 'ed145ac0fc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
