"""on_production

Revision ID: c62e30e8a49d
Revises: 2815bcfd326f
Create Date: 2022-01-08 23:13:53.822309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62e30e8a49d'
down_revision = '2815bcfd326f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
